export enum ComponentType{
    airport= "airport",
    airportRoute = "airportRoute",
    dateRange = "dateRange",
    timeRange = "timeRange",
    airline="airline",
    singleairline="singleairline",
    ceiling="ceiling",
    windSpeed="windSpeed",
    windDirection="windDirection",
    temperature="temperature",
    tailnumber="tailnumber",
    aircraftType="aircraftType",
    flightNumber="flightNumber",
    grouping="grouping",
    rounding="rounding",
    date="date",
    cancelled='cancelled',
    userList='userList',
    optionList='optionList'
}